#!/bin/bash
#
# compile_loader.sh — Compile reflective_loader.c to raw shellcode,
# then generate a C header with the shellcode as a byte array.
#
# Usage: ./scripts/compile_loader.sh
#
# Output: agent_c/include/loader_bin.h
#
# Requirements: x86_64-w64-mingw32-gcc (mingw-w64)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SRC="$PROJECT_ROOT/agent_c/src/reflective_loader.c"
OUT_DIR="$PROJECT_ROOT/agent_c/include"
BUILD_DIR="$PROJECT_ROOT/agent_c/build"

CC="x86_64-w64-mingw32-gcc"
OBJCOPY="x86_64-w64-mingw32-objcopy"

# Check tools
if ! command -v "$CC" &>/dev/null; then
    echo "[-] $CC not found. Install: sudo apt install mingw-w64"
    exit 1
fi
if ! command -v "$OBJCOPY" &>/dev/null; then
    echo "[-] $OBJCOPY not found. Install: sudo apt install mingw-w64"
    exit 1
fi

mkdir -p "$BUILD_DIR"

echo "[*] Compiling reflective loader to object file..."
$CC -c -Os \
    -fno-asynchronous-unwind-tables \
    -fno-ident \
    -nostdlib \
    -fno-stack-protector \
    -fno-exceptions \
    -mno-red-zone \
    -fno-jump-tables \
    -Wall \
    -o "$BUILD_DIR/reflective_loader.o" \
    "$SRC"

echo "[*] Extracting .text section as raw shellcode..."
$OBJCOPY -O binary -j .text \
    "$BUILD_DIR/reflective_loader.o" \
    "$BUILD_DIR/reflective_loader.bin"

LOADER_SIZE=$(stat -c%s "$BUILD_DIR/reflective_loader.bin" 2>/dev/null || stat -f%z "$BUILD_DIR/reflective_loader.bin")
echo "[*] Loader shellcode: $LOADER_SIZE bytes"

echo "[*] Generating loader_bin.h..."
cat > "$OUT_DIR/loader_bin.h" << 'HEADER_TOP'
/*
 * loader_bin.h — Auto-generated reflective PE loader shellcode.
 *
 * Generated by scripts/compile_loader.sh from agent_c/src/reflective_loader.c
 * DO NOT EDIT — regenerate with: ./scripts/compile_loader.sh
 */
#ifndef LOADER_BIN_H
#define LOADER_BIN_H

HEADER_TOP

# Generate the byte array using xxd
echo "static const unsigned char reflective_loader_bin[] = {" >> "$OUT_DIR/loader_bin.h"
xxd -i < "$BUILD_DIR/reflective_loader.bin" | sed 's/^/    /' >> "$OUT_DIR/loader_bin.h"
echo "};" >> "$OUT_DIR/loader_bin.h"
echo "" >> "$OUT_DIR/loader_bin.h"
echo "#define REFLECTIVE_LOADER_SIZE sizeof(reflective_loader_bin)" >> "$OUT_DIR/loader_bin.h"
echo "" >> "$OUT_DIR/loader_bin.h"
echo "/* Real loader compiled — not placeholder */" >> "$OUT_DIR/loader_bin.h"
echo "#define REFLECTIVE_LOADER_READY 1" >> "$OUT_DIR/loader_bin.h"
echo "" >> "$OUT_DIR/loader_bin.h"
echo "#endif /* LOADER_BIN_H */" >> "$OUT_DIR/loader_bin.h"

echo "[+] Generated $OUT_DIR/loader_bin.h ($LOADER_SIZE bytes of shellcode)"

# Cleanup
rm -f "$BUILD_DIR/reflective_loader.o" "$BUILD_DIR/reflective_loader.bin"
rmdir "$BUILD_DIR" 2>/dev/null || true
